/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.gestionescuola;

import java.io.FileWriter;
import java.io.IOException;
import java.time.format.DateTimeFormatter;
import javax.swing.DefaultListModel;

/**
 *
 * @author tss
 */
public class winDialogCorsi extends javax.swing.JDialog {

   

    /**
     * Creates new form winDialogCorsi
     */
    public winDialogCorsi(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //default per oggetti
        spDurataOre.setValue(1);
        refreshLista();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescrizione = new javax.swing.JTextArea();
        lblTitolo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstCorsi = new javax.swing.JList<>();
        spDurataOre = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        FmDataInizio = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        txtLinkCorso = new javax.swing.JTextField();
        btnupdatecorso = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtNomeCorso = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnConfermaDati = new javax.swing.JButton();
        btnCreaCorso = new javax.swing.JButton();
        lblmsg = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtDescrizione.setColumns(20);
        txtDescrizione.setRows(5);
        jScrollPane1.setViewportView(txtDescrizione);

        lblTitolo.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        lblTitolo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitolo.setText("Gestione Corsi");

        jLabel3.setText("Durata Ore:");

        lstCorsi.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstCorsi.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstCorsiValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lstCorsi);

        spDurataOre.setModel(new javax.swing.SpinnerNumberModel(0, null, null, 320));
        spDurataOre.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                spDurataOrePropertyChange(evt);
            }
        });
        spDurataOre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                spDurataOreKeyReleased(evt);
            }
        });

        jLabel4.setText("Data Inizio:");

        jLabel6.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel6.setText("Lista Corsi");

        FmDataInizio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        FmDataInizio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                FmDataInizioKeyReleased(evt);
            }
        });

        jLabel5.setText("Link Corso:");

        btnupdatecorso.setText("update");
        btnupdatecorso.setEnabled(false);
        btnupdatecorso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdatecorsoActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome Corso:");

        txtNomeCorso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomeCorsoKeyReleased(evt);
            }
        });

        jLabel2.setText("Descrizione:");

        btnConfermaDati.setText("conferma dati");
        btnConfermaDati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfermaDatiActionPerformed(evt);
            }
        });

        btnCreaCorso.setText("crea corso");

        btnClose.setText("Chiudi");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addComponent(btnClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitolo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnCreaCorso)
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblmsg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnConfermaDati, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 375, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spDurataOre, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FmDataInizio, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNomeCorso, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnupdatecorso)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLinkCorso, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitolo)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeCorso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(spDurataOre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FmDataInizio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtLinkCorso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnupdatecorso)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnConfermaDati)
                            .addComponent(btnCreaCorso))
                        .addGap(22, 22, 22)
                        .addComponent(lblmsg, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(193, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnClose))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lstCorsiValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstCorsiValueChanged
        // TODO add your handling code here:
        int index = lstCorsi.getSelectedIndex();
      

        String link = txtLinkCorso.getText();
        int durataore = (int) spDurataOre.getValue();

        
        btnCreaCorso.setEnabled(false);
        Corso c = WinGestione.listacorsi.get(index);
        lblmsg.setText("corso selezionato correttamente!");
        txtNomeCorso.setText(c.getNomecorso());
        txtDescrizione.setText(c.getDescrizione());
        txtLinkCorso.setText(c.getLink());
        spDurataOre.setValue(c.getDurataore());
        DateTimeFormatter ddmmaa = DateTimeFormatter.ofPattern("dd/MM/yy");
        String dataok = c.getDatainizio().format(ddmmaa);
        FmDataInizio.setText(dataok);
        btnupdatecorso.setEnabled(true);
        
        refreshLista();
        salvaCorsiCSV();
        validaCorso();

    }//GEN-LAST:event_lstCorsiValueChanged

    private void spDurataOrePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_spDurataOrePropertyChange
        // TODO add your handling code here:
        lblmsg.setText("");

    }//GEN-LAST:event_spDurataOrePropertyChange

    private void spDurataOreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_spDurataOreKeyReleased
        // TODO add your handling code here:
        btnCreaCorso.setEnabled(validaCorso());
    }//GEN-LAST:event_spDurataOreKeyReleased

    private void FmDataInizioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FmDataInizioKeyReleased
        // TODO add your handling code here:
        btnCreaCorso.setEnabled(validaCorso());
    }//GEN-LAST:event_FmDataInizioKeyReleased

    private void btnupdatecorsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdatecorsoActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(btnupdatecorso.getText()) - 1;
        if (!(id < WinGestione.listacorsi.size() & id >= 0)) {
            return;
        }
        String nc = txtNomeCorso.getText();
        String descrizione = txtDescrizione.getText();
        String datainizio = FmDataInizio.getText();
        String ardata[] = datainizio.split("/");
        int d = Integer.parseInt(ardata[0]);
        int m = Integer.parseInt(ardata[1]);
        int y = Integer.parseInt(ardata[2]) + 2000;

        String link = txtLinkCorso.getText();
        int durataore = (int) spDurataOre.getValue();
        Corso newcorso = new Corso(nc, durataore, y, m, d);
        newcorso.setDescrizione(descrizione);
        newcorso.setLink(link);
        WinGestione.listacorsi.set(id, newcorso);
        salvaCorsiCSV();
        lblmsg.setText("corso modificato correttamente");
        id = -1;

        btnupdatecorso.setEnabled(false);

    }//GEN-LAST:event_btnupdatecorsoActionPerformed

    private void txtNomeCorsoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeCorsoKeyReleased
        // TODO add your handling code here:
        btnCreaCorso.setEnabled(validaCorso());
    }//GEN-LAST:event_txtNomeCorsoKeyReleased

    private void btnConfermaDatiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfermaDatiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConfermaDatiActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    
    
    
    
    private void salvaCorsi() {
        //recupero un corso per volta
        //estraggo info tipo string
        //aggiungo info a un testo generico che poi setto in display
        String testoDisplay = "";
        for (int i = 0; i < WinGestione.listacorsi.size(); i++) {
            Corso c = WinGestione.listacorsi.get(i);
            String info = c.getInfo();
            testoDisplay = testoDisplay + info;
        }
        try {
            //creo file corsi.txt
            //ci scrivo dentro testoDisplay
            //lo chiudo se no si blocca
            FileWriter myWriter = new FileWriter("/home/tss/Scuola/corsi.txt");
            myWriter.write(testoDisplay);
            myWriter.close();
        } catch (IOException ex) {
            lblmsg.setText("errore di scrittura file corsi.txt");
        }

    }

    private void salvaCorsiCSV() {
        //recupero un corso per volta
        //estraggo info tipo string
        //aggiungo info a un testo generico che poi setto in display
        String testoDisplay = "nomecorso;durataore;descrizione;datainizio;link\n";
        for (int i = 0; i < WinGestione.listacorsi.size(); i++) {
            Corso c = WinGestione.listacorsi.get(i);
            String info = c.getCSV();
            testoDisplay += info;
        }
        try {
            //creo file corsi.txt
            //ci scrivo dentro testoDisplay
            //lo chiudo se no si blocca
            FileWriter myWriter = new FileWriter("/home/tss/Scuola/corsi.csv");
            myWriter.write(testoDisplay);
            myWriter.close();
        } catch (IOException ex) {
            lblmsg.setText("errore di scrittura file corsi.txt");
        }

    }

    private boolean validaCorso() {
        boolean ret = false;
        boolean koNome = !txtNomeCorso.getText().equals("");
        int val = (int) spDurataOre.getValue();
        boolean koValore = val > 0;
        boolean koData = !FmDataInizio.getText().equals("");

        if (koNome && koData && koValore) {
            ret = true;

        }

        return ret;
    }

    private void refreshLista() {
        DefaultListModel model = new DefaultListModel();
        for (int i = 0; i < WinGestione.listacorsi.size(); i++) {
            String nc = WinGestione.listacorsi.get(i).getNomecorso();
            model.addElement(nc);
        }

        lstCorsi.setModel(model);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(winDialogCorsi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(winDialogCorsi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(winDialogCorsi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(winDialogCorsi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                winDialogCorsi dialog = new winDialogCorsi(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                        
                    }
                
                
            });
                dialog.setVisible(true);
                        }
        
       });
    
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField FmDataInizio;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnConfermaDati;
    private javax.swing.JButton btnCreaCorso;
    private javax.swing.JButton btnupdatecorso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTitolo;
    private javax.swing.JLabel lblmsg;
    private javax.swing.JList<String> lstCorsi;
    private javax.swing.JSpinner spDurataOre;
    private javax.swing.JTextArea txtDescrizione;
    private javax.swing.JTextField txtLinkCorso;
    private javax.swing.JTextField txtNomeCorso;
    // End of variables declaration//GEN-END:variables

                
}