/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.gestionescuola;

import java.io.File;
import java.util.ArrayList;
import java.util.Scanner;

/**
 *
 * @author tss
 */
public class WinGestione extends javax.swing.JFrame {

    static ArrayList<Corso> listacorsi = new ArrayList<Corso>();
    static ArrayList<Anagrafica> listaAnagrafiche= new ArrayList<>();
   
    

    /**     * Creates new form WinGestione
     */
    public WinGestione() {
        initComponents();
        caricaDatiAnagrafica();
        caricaDatiCorsi();
        showCorsi();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private void showCorsi() {
        //recupero un corso per volta
        //estraggo info tipo string
        //aggiungo info a un testo generico che poi setto in display
        String testoDisplay = "";
        for (int i = 0; i < listacorsi.size(); i++) {
            Corso c = listacorsi.get(i);
            String info ="[" + (i+1)+"]" + c.getInfo();
            testoDisplay = info + testoDisplay;
        }
        tpDisplay.setText(testoDisplay);
    }
       public static int getNewIdAnagrafica(){
        int newId = 1;
        if(listaAnagrafiche.size()>0){
        newId = listaAnagrafiche.get(listaAnagrafiche.size()-1).getId_anagrafica()+1;
        }
        
        return newId;
    }
    

    

    public void caricaDatiCorsi() {
        try {
            //aprire il file /tss/home/scuola/corsi.csv
            File fileCSV = new File("/home/tss/Scuola/corsi.csv"); 
            //creo scanner per leggere una riga alla volta
            Scanner lettore = new Scanner(fileCSV);
            //estrarre una riga per volta
            int n = 1;
            while(lettore.hasNextLine()){
            String riga = lettore.nextLine();
            if(n>1){
               String dati[] = riga.split(";");
               //dati[0} nome corso, dati [1] durata, etc.
               String nc = dati[0];
               int durata = Integer.parseInt(dati[1]);
               String des = dati[2];
               String d[] = dati[3].split("-");
               int y = Integer.parseInt(d[0]);
               int m = Integer.parseInt(d[1]);
               int g = Integer.parseInt(d[2]);
               String link = "";
               if (dati.length>=5){
                link = dati[4]; 
                
            }           
               ////
               Corso c = new Corso(nc, durata, y, m, g);
               if(dati.length>=6){
               String registro = dati[5];
               String[] regid = registro.split(",");
               for(String sid:regid){
                int id=Integer.parseInt(sid);
                Anagrafica al=getAlunnoById(id);
                c.insertAlunno(al);
               }
               }
               c.setDescrizione(des);
               c.setLink(link);
               //il corso è pronto, lo aggiungiamo alla lista
               listacorsi.add(c);
            }
            n++;
            //la riga la taglio in tanti pezzi col ; in un array
            //elemento per elemento dell'array lo imposto ad un corso
            //aggiungo il corso alla lista e via così dicendo
            }
                        

        } catch (Exception e) {

        }

    }
 
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitolo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tpDisplay = new javax.swing.JTextPane();
        lblmsg = new javax.swing.JLabel();
        btnGestioneCorsi = new javax.swing.JButton();
        btnGestioneAnagrafica = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        lblTitolo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitolo.setText("Gestione Scuola");

        jScrollPane2.setViewportView(tpDisplay);

        btnGestioneCorsi.setText("Gestione Corsi");
        btnGestioneCorsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestioneCorsiActionPerformed(evt);
            }
        });

        btnGestioneAnagrafica.setText("Gestione Anagrafica");
        btnGestioneAnagrafica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestioneAnagraficaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblTitolo, javax.swing.GroupLayout.PREFERRED_SIZE, 1074, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblmsg, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnGestioneAnagrafica, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                            .addComponent(btnGestioneCorsi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(121, 121, 121))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitolo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGestioneCorsi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGestioneAnagrafica)
                        .addGap(274, 274, 274)
                        .addComponent(lblmsg, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGestioneCorsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestioneCorsiActionPerformed
        // TODO add your handling code here:
        new winDialogCorsi(this,true).setVisible(true);
    }//GEN-LAST:event_btnGestioneCorsiActionPerformed

    private void btnGestioneAnagraficaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestioneAnagraficaActionPerformed
        // TODO add your handling code here:
        //apertura finestra dialogo per caricamento e gestione anagrafica
        new winDialogAnagraficha(this,true).setVisible(true);
        
    }//GEN-LAST:event_btnGestioneAnagraficaActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        showCorsi();
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WinGestione.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WinGestione.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WinGestione.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WinGestione.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WinGestione().setVisible(true);
            }
        });
    }
    public static void caricaDatiAnagrafica() {
        try {
            //aprire il file /tss/home/scuola/corsi.csv
            File fileCSV = new File("/home/tss/Scuola/anagrafiche.csv"); 
            //creo scanner per leggere una riga alla volta
            Scanner lettore = new Scanner(fileCSV);
            //estrarre una riga per volta
            int n = 1;
            while(lettore.hasNextLine()){
            String riga = lettore.nextLine();
            if(n>1){
                String[]dati=riga.split(";");
               
               
               int id= Integer.parseInt(dati[0]);
               String Cognome = dati[1];
               String Nome = dati[2];
               String mail = dati[3];
               Anagrafica a = new Anagrafica(id, Cognome, Nome, mail);
               //il corso è pronto, lo aggiungiamo alla lista
                listaAnagrafiche.add(a);
            }
            n++;
           
            }
                        

        } catch (Exception e) {

        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGestioneAnagrafica;
    private javax.swing.JButton btnGestioneCorsi;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTitolo;
    private javax.swing.JLabel lblmsg;
    private javax.swing.JTextPane tpDisplay;
    // End of variables declaration//GEN-END:variables

    public static Anagrafica getAlunnoById(int id) {
        for(Anagrafica a:listaAnagrafiche){
            if(id==a.getId_anagrafica())
                return a;
        }
        return null;
    }
}
