/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package it.tss.gestscuola;

import java.io.FileWriter;
import java.io.IOException;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author tss
 */
public class WinGestioneCorso extends javax.swing.JFrame {
    int idcorso = -1;
    /**
     * Creates new form WinGestioneCorso
     */
    public WinGestioneCorso() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNomeCorso = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescrizione = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        spDurataOre = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        FmDataInizio = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        txtLinkCorso = new javax.swing.JTextField();
        btnselcorso = new javax.swing.JButton();
        btnupdatecorso = new javax.swing.JButton();
        idCorsoUpdate = new javax.swing.JTextField();
        btnCreaCorso = new javax.swing.JButton();
        lblmsg = new javax.swing.JLabel();
        lblTitolo = new javax.swing.JLabel();
        btnPrepNewCorso = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome Corso:");

        txtNomeCorso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomeCorsoKeyReleased(evt);
            }
        });

        jLabel2.setText("Descrizione:");

        txtDescrizione.setColumns(20);
        txtDescrizione.setRows(5);
        jScrollPane1.setViewportView(txtDescrizione);

        jLabel3.setText("Durata Ore:");

        spDurataOre.setModel(new javax.swing.SpinnerNumberModel(0, null, null, 320));
        spDurataOre.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                spDurataOrePropertyChange(evt);
            }
        });
        spDurataOre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                spDurataOreKeyReleased(evt);
            }
        });

        jLabel4.setText("Data Inizio:");

        FmDataInizio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        FmDataInizio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                FmDataInizioKeyReleased(evt);
            }
        });

        jLabel5.setText("Link Corso:");

        btnselcorso.setText("edit corso");
        btnselcorso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnselcorsoActionPerformed(evt);
            }
        });

        btnupdatecorso.setText("aggiorna corso");
        btnupdatecorso.setEnabled(false);
        btnupdatecorso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdatecorsoActionPerformed(evt);
            }
        });

        idCorsoUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idCorsoUpdateActionPerformed(evt);
            }
        });

        btnCreaCorso.setText("conferma nuovo corso");
        btnCreaCorso.setEnabled(false);
        btnCreaCorso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreaCorsoActionPerformed(evt);
            }
        });

        lblTitolo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitolo.setText("Gestione Corsi");

        btnPrepNewCorso.setText("Nuovo corso");
        btnPrepNewCorso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrepNewCorsoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitolo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 121, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNomeCorso, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spDurataOre, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(8, 8, 8)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FmDataInizio, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLinkCorso, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(108, 108, 108)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnupdatecorso)
                    .addComponent(btnselcorso, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(idCorsoUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCreaCorso, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                            .addComponent(btnPrepNewCorso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(lblmsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(lblTitolo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeCorso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spDurataOre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FmDataInizio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLinkCorso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(idCorsoUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnselcorso))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnPrepNewCorso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btnupdatecorso))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCreaCorso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblmsg, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void spDurataOrePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_spDurataOrePropertyChange
        // TODO add your handling code here:
        lblmsg.setText("");
        
    }//GEN-LAST:event_spDurataOrePropertyChange

    private void btnselcorsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnselcorsoActionPerformed
        // TODO add your handling code here:
        idcorso= Integer.parseInt(idCorsoUpdate.getText())-1;
        if(!(idcorso<WinGestione.listacorsi.size()& idcorso >=0 ))
        return;
        btnselcorso.setEnabled(false);
        btnupdatecorso.setEnabled(true);
        btnCreaCorso.setEnabled(false);
        Corso c = WinGestione.listacorsi.get(idcorso);
        lblmsg.setText("corso selezionato correttamente!");
        txtNomeCorso.setText(c.getNomecorso());
        txtDescrizione.setText(c.getDescrizione());
        txtLinkCorso.setText(c.getLink());
        spDurataOre.setValue(c.getDurataore());
        DateTimeFormatter ddmmaa= DateTimeFormatter.ofPattern("dd/MM/yy");
        String dataok=c.getDatainizio().format(ddmmaa);
        FmDataInizio.setText(dataok);

    }//GEN-LAST:event_btnselcorsoActionPerformed

    private void btnupdatecorsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdatecorsoActionPerformed
        // TODO add your handling code here:
        int id= Integer.parseInt(idCorsoUpdate.getText())-1;
        if(!(id<WinGestione.listacorsi.size()& id >=0 ))
        return;
        String nc = txtNomeCorso.getText();
        String descrizione = txtDescrizione.getText();
        String datainizio = FmDataInizio.getText();
        String ardata[] = datainizio.split("/");
        int d = Integer.parseInt(ardata[0]);
        int m = Integer.parseInt(ardata[1]);
        int y = Integer.parseInt(ardata[2]) + 2000;

        String link = txtLinkCorso.getText();
        int durataore = (int) spDurataOre.getValue();
        Corso newcorso = new Corso(nc, durataore, y, m, d);
        newcorso.setDescrizione(descrizione);
        newcorso.setLink(link);
        WinGestione.listacorsi.set(id, newcorso);
        salvaCorsiCSV();
        lblmsg.setText("corso modificato correttamente");
        idcorso=-1;

        btnselcorso.setEnabled(true);
        btnupdatecorso.setEnabled(false);
        

    }//GEN-LAST:event_btnupdatecorsoActionPerformed

    private void idCorsoUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idCorsoUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idCorsoUpdateActionPerformed

    private void btnCreaCorsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreaCorsoActionPerformed
        // TODO add your handling code here:
        //recuperiamo i dati da interfaccia
        String nc = txtNomeCorso.getText();
        String descrizione = txtDescrizione.getText();
        String datainizio = FmDataInizio.getText();
        String ardata[] = datainizio.split("/");
        int d = Integer.parseInt(ardata[0]);
        int m = Integer.parseInt(ardata[1]);
        int y = Integer.parseInt(ardata[2]);

        String link = txtLinkCorso.getText();
        int durataore = (int) spDurataOre.getValue();
        Corso newcorso = new Corso(nc, durataore, y, m, d);
        newcorso.setDescrizione(descrizione);
        newcorso.setLink(link);
        WinGestione.listacorsi.add(newcorso);
        lblmsg.setText("corso creato correttamente!");
        txtNomeCorso.setText("");
        txtDescrizione.setText("");
        txtLinkCorso.setText("");
        spDurataOre.setValue(0);
        FmDataInizio.setText("");
        salvaCorsi();
        salvaCorsiCSV();
    }//GEN-LAST:event_btnCreaCorsoActionPerformed

    private void btnPrepNewCorsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrepNewCorsoActionPerformed
        lblmsg.setText("ora puoi inserire i dati del corso");
        txtNomeCorso.setText("");
        txtDescrizione.setText("");
        txtLinkCorso.setText("");
        spDurataOre.setValue(0);
        FmDataInizio.setText("");
        btnupdatecorso.setEnabled(false);
        
    }//GEN-LAST:event_btnPrepNewCorsoActionPerformed

    private void txtNomeCorsoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeCorsoKeyReleased
        // TODO add your handling code here:
        btnCreaCorso.setEnabled(validaCorso());
    }//GEN-LAST:event_txtNomeCorsoKeyReleased

    private void spDurataOreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_spDurataOreKeyReleased
        // TODO add your handling code here:
        btnCreaCorso.setEnabled(validaCorso());
    }//GEN-LAST:event_spDurataOreKeyReleased

    private void FmDataInizioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FmDataInizioKeyReleased
        // TODO add your handling code here:
        btnCreaCorso.setEnabled(validaCorso());
    }//GEN-LAST:event_FmDataInizioKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WinGestioneCorso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WinGestioneCorso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WinGestioneCorso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WinGestioneCorso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WinGestioneCorso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField FmDataInizio;
    private javax.swing.JButton btnCreaCorso;
    private javax.swing.JButton btnPrepNewCorso;
    private javax.swing.JButton btnselcorso;
    private javax.swing.JButton btnupdatecorso;
    private javax.swing.JTextField idCorsoUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitolo;
    private javax.swing.JLabel lblmsg;
    private javax.swing.JSpinner spDurataOre;
    private javax.swing.JTextArea txtDescrizione;
    private javax.swing.JTextField txtLinkCorso;
    private javax.swing.JTextField txtNomeCorso;
    // End of variables declaration//GEN-END:variables
private void salvaCorsi() {
        //recupero un corso per volta
        //estraggo info tipo string
        //aggiungo info a un testo generico che poi setto in display
        String testoDisplay = "";
        for (int i = 0; i < WinGestione.listacorsi.size(); i++) {
            Corso c = WinGestione.listacorsi.get(i);
            String info = c.getInfo();
            testoDisplay = testoDisplay + info;
        }
        try {
            //creo file corsi.txt
            //ci scrivo dentro testoDisplay
            //lo chiudo se no si blocca
            FileWriter myWriter = new FileWriter("/home/tss/Scuola/corsi.txt");
            myWriter.write(testoDisplay);
            myWriter.close();
        } catch (IOException ex) {
            lblmsg.setText("errore di scrittura file corsi.txt");
        }

    }

    private void salvaCorsiCSV() {
        //recupero un corso per volta
        //estraggo info tipo string
        //aggiungo info a un testo generico che poi setto in display
        String testoDisplay = "nomecorso;durataore;descrizione;datainizio;link\n";
        for (int i = 0; i < WinGestione.listacorsi.size(); i++) {
            Corso c = WinGestione.listacorsi.get(i);
            String info = c.getCSV();
            testoDisplay += info;
        }
        try {
            //creo file corsi.txt
            //ci scrivo dentro testoDisplay
            //lo chiudo se no si blocca
            FileWriter myWriter = new FileWriter("/home/tss/Scuola/corsi.csv");
            myWriter.write(testoDisplay);
            myWriter.close();
        } catch (IOException ex) {
            lblmsg.setText("errore di scrittura file corsi.txt");
        }

    }
    private boolean validaCorso(){
    boolean ret = false;
     boolean koNome = !txtNomeCorso.getText().equals("");
     int val= (int) spDurataOre.getValue();
     boolean koValore = val>0;
     boolean koData=!FmDataInizio.getText().equals("");
     
     if(koNome && koData && koValore){
         ret=true;
          
       
        }
    
    return ret;
}
}
